auth-token:
  type: string
  name: Auth Token
  description: Token for authenticating to BWT's HTTP API
  nullable: false
  pattern: '^[^\n:]+$'
  pattern-description: May not contain newline or ":"
  copyable: true
  masked: true
  default:
    charset: a-z,A-Z,0-9
    len: 22
bitcoind:
  type: union
  name: Bitcoin Core
  description: |
    The Bitcoin Core node to connect to:
      - internal: The Bitcoin Core and Proxy services installed to your Embassy
      - external: An unpruned Bitcoin Core node running on a different device
      - quick-connect: A Quick Connect URL for an unpruned Bitcoin Core node
  tag: type
  default: internal
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to bwt
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        # index: 'users.[first(item => ''item.name = "bwt")].name'
        selector: '$.users[?(@.name == "bwt")].name'
        multi: false
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to bwt
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        # index: 'users.[first(item => ''item.name = "bwt")].password'
        selector: '$.users[?(@.name == "bwt")].password'
        multi: false
    external:
      host:
        type: string
        name: Public Address
        description: The public address of your Bitcoin Core server
        nullable: false
      rpc-user:
        type: string
        name: RPC Username
        description: The username for the RPC user on your Bitcoin Core RPC server
        nullable: false
      rpc-password:
        type: string
        name: RPC Password
        description: The password for the RPC user on your Bitcoin Core RPC server
        nullable: false
      rpc-port:
        type: number
        name: RPC Port
        description: The port that your Bitcoin Core RPC server is bound to
        nullable: false
        range: "[0,65535]"
        integral: true
        default: 8332
    quick-connect:
      quick-connect-url:
        type: string
        name: Quick Connect URL
        description: |
          The Quick Connect URL for your Bitcoin Core RPC server
          NOTE: BWT will not accept a .onion url for this option
        nullable: false
        pattern: 'btcstandup://[^:]*:[^@]*@[a-zA-Z0-9.-]+:[0-9]+(/(\?(label=.+)?)?)?'
        pattern-description: Must be a valid Quick Connect URL. For help, check out https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Quick-Connect-API.md
# https://help.blockonomics.co/support/solutions/articles/33000248743-bitcoin-wallet-and-xpub
xpubs:
  type: list
  name: Standard Extended Public Keys
  description: |
    A list of standard extended public keys, each corresponding to a wallet to track. 
    Extended public keys begin with:
      "xpub" for P2PKH wallets (contains addresses beginning with 1)
      "ypub" for P2SH-P2WPKH wallets ("Segwit backwards compatible") (contains addresses beginning with 3)
      "zpub" for P2WPKH wallets ("bech32") (for wallets with addresses beginning with bc1)

    Standard extended pubkeys are the root of a tree 
  range: "[0,*)"
  subtype: string
  default: []
  spec:
    key: 
      type: string
      name: Extended Public Key
      description: The extended public key for the wallet to track
      default: "xpub..."
      nullable: false
      copyable: true
bare-xpubs:
  type: list
  name: Bare Extended Public Keys
  description: |
    A list of bare extended public keys, each corresponding to a wallet to track. 
    Extended public keys begin with:
      "xpub" for P2PKH wallets (contains addresses beginning with 1)
      "ypub" for P2SH-P2WPKH wallets ("Segwit backwards compatible") (contains addresses beginning with 3)
      "zpub" for P2WPKH wallets ("bech32") (for wallets with addresses beginning with bc1)

    "Bare" extended pubkeys are pubkeys which track
  range: "[0,*)"
  subtype: string
  default: []
  spec:
    key: 
      type: string
      name: Extended Public Key
      description: The bare extended public key for the wallet to track
      default: "xpub..."
      nullable: false
      copyable: true
descriptors:
  type: list
  name: Wallet Desciptors
  description: Descriptor for wallet to track
  range: "[0,*)"
  subtype: string
  default: []
  spec:
    key: 
      type: string
      name: Wallet Desciptor
      description: The descriptor for the wallet to track
      default: "wpkh(xpub../0/*);wpkh(xpub../1/*)"
      nullable: false
      copyable: true
rescan-since:
  type: string
  name: Rescan Date
  description: |
          Start date for wallet history rescan. Accepts YYYY-MM-DD formatted strings, unix timestamps, or 'now' to
          watch for new transactions only  [default: 0]
  default: "now"
  nullable: true
bitcoind-wallet:
  type: string
  name: Bitcoind Wallet Name
  description: |
          Name of the wallet to use inside bitcoind
  default: "bwt"
  nullable: true
create-wallet-if-missing:
  type: boolean
  name: Create Wallet If Missing
  description: If enabled, this option will automatically create, inside bitcoin core's data directory, the wallet specified in "Bitcoind Wallet Name"
  default: true
